import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { UserProvider } from "../app/context/usercontext"; // Adjust the import path as necessary
import type { AppProps } from "next/app";
import Header from "./components/nav";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "DrAIT MIS",
  icons: {
    icon: '/favicon.ico', // Path to your favicon
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <UserProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Header title="Dr Ambedkar Institute of Technology" />
          {children}
        </body>
      </html>
    </UserProvider>
  );
}

